# Docker Full Module Installation

version: '3'
services:
  # Server Module
  project-alice-server:
    image: ghcr.io/xinnan-tech/xiaozhi-esp32-server:server_latest
    container_name: project-alice-server
    depends_on:
      - project-alice-server-db
      - project-alice-server-redis
    restart: always
    networks:
      - default
    ports:
      # WebSocket Server
      - "8000:8000"
      # HTTP service port, used for vision analysis API
      - "8003:8003"
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Asia/Bangkok
      - GOOGLE_MAPS_API_KEY=AIzaSyCiwPDPNc6T101SZO72hfYRlj0OZud1Ky4
      - GOOGLE_CALENDAR_ID=atty.dhamanoon@gmail.com
    volumes:
      # Configuration file directory
      - ./data:/opt/xiaozhi-esp32-server/data
      # Model file mount (Very Important)
      - ./models/SenseVoiceSmall/model.pt:/opt/xiaozhi-esp32-server/models/SenseVoiceSmall/model.pt

  # Manager API and Manager Web Module
  project-alice-server-web:
    image: ghcr.io/xinnan-tech/xiaozhi-esp32-server:web_latest
    container_name: project-alice-server-web
    restart: always
    networks:
      - default
    depends_on:
      project-alice-server-db:
        condition: service_healthy
      project-alice-server-redis:
        condition: service_healthy
    ports:
      # Control Panel / Admin Console
      - "8002:8002"
    environment:
      - TZ=Asia/Bangkok
      - SPRING_DATASOURCE_DRUID_URL=jdbc:mysql://project-alice-server-db:3306/project_alice_server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Bangkok&nullCatalogMeansCurrent=true&connectTimeout=30000&socketTimeout=30000&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      - SPRING_DATASOURCE_DRUID_USERNAME=root
      - SPRING_DATASOURCE_DRUID_PASSWORD=54414B415255
      - SPRING_DATA_REDIS_HOST=project-alice-server-redis
      - SPRING_DATA_REDIS_PASSWORD=
      - SPRING_DATA_REDIS_PORT=6379
    volumes:
      # Uploaded files directory
      - ./uploadfile:/uploadfile

  # Database Module
  project-alice-server-db:
    image: mysql:latest
    container_name: project-alice-server-db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    networks:
      - default
    expose:
      - 3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=54414B415255
      - MYSQL_DATABASE=project_alice_server
      - MYSQL_INITDB_ARGS="--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  # Redis Module
  project-alice-server-redis:
    image: redis:8.0
    expose:
      - 6379
    container_name: project-alice-server-redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - default

networks:
  default:
