# Docker安装Server
version: '3'
services:
  xiaozhi-esp32-server:
    image: ghcr.io/xinnan-tech/xiaozhi-esp32-server:server_latest
    container_name: project-alice-server
    restart: always
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Asia/Bangkok
    ports:
      # WebSocket Server
      - "8000:8000"
      # HTTP Server (OTA / Vision API)
      - "8003:8003"
    volumes:
      # 配置文件目录 (ต้องมี config.yaml อยู่ข้างใน)
      - ./data:/opt/xiaozhi-esp32-server/data
      # 模型文件挂接 (ต้องดาวน์โหลด model.pt มาวางก่อนรัน)
      - ./models/SenseVoiceSmall/model.pt:/opt/xiaozhi-esp32-server/models/SenseVoiceSmall/model.pt
